---
version: "2"
services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Washington
            - URL=api.budgetml.com
            - SUBDOMAINS=srgan,
            - VALIDATION=http
            - STAGING=false #optional
        volumes:
            - ${BUDGET_NGINX_PATH}:/config/nginx/proxy-confs/app.subdomain.conf
            - ${BUDGET_CERTS_PATH}:/config/etc/letsencrypt/
        ports:
            - 443:443
            - 80:80 #optional
        restart: unless-stopped
        networks: 
            - production

    budgetml:
        image: budgetml
        container_name: budgetml
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80 # maps port 80 in our container to 8080
        restart: unless-stopped
        networks: 
            - production

networks:
    production:
